2021-10-28 21:15:07.782 | INFO     |  5390 | __main__:create_enclosure:55 | Creating generic enclosure, platform='None'
2021-10-28 21:15:07.788 | INFO     |  5390 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-28 21:15:07.793 | INFO     |  5390 | mycroft.client.enclosure.base:create_gui_service:473 | Starting message bus for GUI...
2021-10-28 21:15:07.796 | INFO     |  5390 | mycroft.client.enclosure.base:create_gui_service:483 | GUI Message bus started!
2021-10-28 21:15:07.797 | INFO     |  5390 | mycroft.enclosure.display_manager:init_display_manager_bus_connection:152 | Connecting display manager to messagebus
2021-10-28 21:15:07.798 | INFO     |  5390 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-28 21:15:07.800 | INFO     |  5390 | mycroft_bus_client.client.client | Connected
2021-10-28 21:15:08.008 | INFO     |  5390 | mycroft_bus_client.client.client | Connected
2021-10-28 21:15:08.010 | INFO     |  5390 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-28 21:15:08.014 | INFO     |  5390 | __main__:on_ready:26 | Enclosure started!
2021-10-28 21:17:09.749 | INFO     |  5390 | __main__:on_stopping:30 | Enclosure is shutting down...
2021-10-28 21:17:12.140 | ERROR    |  5390 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7fd2d8507310>>: cannot schedule new futures after shutdown
2021-10-28 21:17:12.141 | ERROR    |  5390 | mycroft_bus_client.client.client | === RuntimeError('cannot schedule new futures after shutdown') ===
Traceback (most recent call last):
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 407, in _callback
    callback(self, *args)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 182, in on_message
    self.emitter.emit('message', message)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 113, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_base.py", line 96, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/pyee/_executor.py", line 50, in _emit_run
    future = self._executor.submit(f, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
2021-10-28 21:17:12.142 | ERROR    |  5390 | mycroft_bus_client.client.client | Exception closing websocket: RuntimeError('cannot schedule new futures after shutdown')
2021-10-28 21:17:12.142 | WARNING  |  5390 | mycroft_bus_client.client.client | Message Bus Client will reconnect in 5.0 seconds.
