2021-10-26 13:43:02.233 | INFO     |  5705 | __main__:main:46 | Starting Audio Service
2021-10-26 13:43:02.234 | INFO     |  5705 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 13:43:02.239 | INFO     |  5705 | mycroft_bus_client.client.client | Connected
2021-10-26 13:43:02.240 | INFO     |  5705 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 13:43:02.244 | WARNING  |  5705 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-26 13:43:02.413 | ERROR    |  5705 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-26 13:43:02.414 | ERROR    |  5705 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-26 13:43:02.455 | ERROR    |  5705 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-26 13:43:17.105 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:43:47.635 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:43:47.636 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.028 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.105 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.114 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.130 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.131 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.141 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:18.151 | ERROR    |  5705 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:24.261 | ERROR    |  5705 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f181d8caad0>>: cannot schedule new futures after shutdown
2021-10-26 13:44:24.262 | ERROR    |  5705 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f181d8caad0>>: cannot schedule new futures after shutdown
2021-10-26 13:44:24.262 | ERROR    |  5705 | websocket | error from callback <bound method MessageBusClient.on_message of <mycroft.messagebus.client.client.MessageBusClient object at 0x7f181d8caad0>>: cannot schedule new futures after shutdown
2021-10-26 13:44:36.622 | INFO     |  7335 | __main__:main:46 | Starting Audio Service
2021-10-26 13:44:36.623 | INFO     |  7335 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-26 13:44:36.626 | INFO     |  7335 | mycroft_bus_client.client.client | Connected
2021-10-26 13:44:36.628 | INFO     |  7335 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-26 13:44:36.632 | WARNING  |  7335 | mycroft.tts.tts:clear_cache:428 | This method is deprecated, use TextToSpeechCache.clear
2021-10-26 13:44:36.891 | ERROR    |  7335 | mycroft.tts.mimic_tts:validate_connection:226 | Mimic executable not found
2021-10-26 13:44:36.891 | ERROR    |  7335 | mycroft.tts.tts:create:625 | The TTS could not be loaded.
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 221, in validate_connection
    subprocess.call([mimic_bin, '--version'])
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/os.py", line 812, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 614, in create
    tts.validator.validate()
  File "/opt/mycroft-core/mycroft/tts/tts.py", line 500, in validate
    self.validate_connection()
  File "/opt/mycroft-core/mycroft/tts/mimic_tts.py", line 229, in validate_connection
    from err
Exception: Mimic was not found. Run install-mimic.sh to install it.
2021-10-26 13:44:36.892 | ERROR    |  7335 | __main__:on_error:37 | Audio service failed to launch (Exception('Mimic was not found. Run install-mimic.sh to install it.')).
2021-10-26 13:44:38.999 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:39.396 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:39.795 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:40.194 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:41.218 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:49.404 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:49.828 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:50.221 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:50.577 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:51.241 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:51.614 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:59.059 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:44:59.923 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
2021-10-26 13:45:00.461 | ERROR    |  7335 | mycroft.audio.speech:handle_speak:99 | Error in mute_and_speak
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/opt/mycroft-core/mycroft/audio/speech.py", line 120, in mute_and_speak
    tts.playback.stop()
AttributeError: 'NoneType' object has no attribute 'playback'
Exception ignored in: <module 'threading' from '/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
